set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RK3562_TOOLCHAIN_ROOT "$ENV{RK3562_TOOLCHAIN_ROOT}" CACHE PATH "Buildroot aarch64 toolchain root")
if (NOT RK3562_TOOLCHAIN_ROOT)
  set(RK3562_TOOLCHAIN_ROOT "/home/pve/MESA_for_pen/toolchains/aarch64--glibc--stable-2018.11-1" CACHE PATH "Buildroot aarch64 toolchain root" FORCE)
endif()

set(RK3562_TARGET_TRIPLE "aarch64-buildroot-linux-gnu" CACHE STRING "Buildroot target triple")
set(RK3562_DEPS_ROOT "$ENV{RK3562_DEPS_ROOT}" CACHE PATH "RK3562 target dependency sysroot")

set(CMAKE_C_COMPILER "${RK3562_TOOLCHAIN_ROOT}/bin/${RK3562_TARGET_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${RK3562_TOOLCHAIN_ROOT}/bin/${RK3562_TARGET_TRIPLE}-g++")
set(CMAKE_AR "${RK3562_TOOLCHAIN_ROOT}/bin/${RK3562_TARGET_TRIPLE}-ar")
set(CMAKE_RANLIB "${RK3562_TOOLCHAIN_ROOT}/bin/${RK3562_TARGET_TRIPLE}-ranlib")
set(CMAKE_STRIP "${RK3562_TOOLCHAIN_ROOT}/bin/${RK3562_TARGET_TRIPLE}-strip")
set(PKG_CONFIG_EXECUTABLE "${RK3562_TOOLCHAIN_ROOT}/bin/pkg-config")

set(CMAKE_SYSROOT "${RK3562_TOOLCHAIN_ROOT}/${RK3562_TARGET_TRIPLE}/sysroot")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

if (RK3562_DEPS_ROOT)
  list(APPEND CMAKE_FIND_ROOT_PATH "${RK3562_DEPS_ROOT}")
  set(ENV{PKG_CONFIG_LIBDIR} "${RK3562_DEPS_ROOT}/usr/lib/pkgconfig:${RK3562_DEPS_ROOT}/usr/share/pkgconfig")
  set(ENV{PKG_CONFIG_SYSROOT_DIR} "${RK3562_DEPS_ROOT}")
  set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--allow-shlib-undefined -Wl,-rpath-link,${RK3562_DEPS_ROOT}/usr/lib")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Wl,--allow-shlib-undefined -Wl,-rpath-link,${RK3562_DEPS_ROOT}/usr/lib")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
